# ==============================================================================
# WORKFLOW: Daily Google Play Review Ingestion to Snowflake
# ==============================================================================

name: Daily Review Ingestion

on:
  # 1. Scheduled Run
  schedule:
    - cron: '0 12 * * *'

  # 2. Manual Run
  workflow_dispatch:

jobs:
  scrape-and-ingest:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read 

    steps:
      # Step 1: Checks out your repository's code onto the runner
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      # Step 2: Sets up a specific Python version for consistency
      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' 

      # Step 3: Installs the exact Python libraries defined in requirements.txt
      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      # Step 4: Executes the Python ingestion script
      - name: Run Python Ingestion Script
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        run: python ingest_reviews_optimized.py 