# This is a GitHub Actions workflow file
# It defines a scheduled job to run our Python ingestion script

name: Daily Review Ingestion

# This section defines the schedule
on:
  schedule:
    # Runs At 12:00 UTC every day
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  scrape-and-ingest:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up a Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install all the required libraries
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-play-scraper snowflake-connector-python pandas sqlalchemy python-dotenv pyarrow

      # Step 4: Run the ingestion script
      - name: Run ingestion script
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        run: python ingest_reviews.py